server:
  port: 8282

simple:
  dictionary:
    log:
      method:
        enabled: true
      executionTime:
        enabled: true

feign:
  hystrix:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
