server:
  port: 8282

simple:
  dictionary:
    api:
      id: abd32269
      key: 02c6108e3e428c200357c398a6d0359c
    log:
      method:
        enabled: false
      executionTime:
        enabled: true
    clients:
      dictionary:
        url: https://od-api.oxforddictionaries.com:443/api/v1
    messages:
      word:
        notFound: Eish...Askies, word not found.
      cache:
        namesNotFound: Eish...Askies, cache names not found.
        keysNotFound: Eish...Askies, cache keys not found.

feign:
  hystrix:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE